steps:
  # Step 1: Install Dependencies
  - name: 'node:18'
    id: 'Install Dependencies'
    entrypoint: npm
    args: ['install']

  # Step 2: Build the Next.js app with Hardcoded Environment Variables
  - name: 'node:18'
    id: 'Build App'
    entrypoint: bash
    args:
      - '-c'
      - |
        export NEXT_PUBLIC_SUPABASE_URL=https://pdcbzxohtjosfeibqjmz.supabase.co
        export NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkY2J6eG9odGpvc2ZlaWJxam16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1ODI2NjQsImV4cCI6MjA1NDE1ODY2NH0.zPoNcVre2qyGTcF4rxYXAbNraQq9AhxYv2nGiVkyOfM
        npm run build

  # Step 3: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker Image'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app', '.']

  # Step 4: Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Image to GCR'
    args: ['push', 'gcr.io/$PROJECT_ID/my-app']

  # Step 5: Deploy to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'my-app'
      - '--image=gcr.io/$PROJECT_ID/my-app'
      - '--platform=managed'
      - '--region=us-central1' # Change to your region
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/my-app'
