name: Deploy to GCP

on:
  push:
    branches:
      - main  # Runs when pushing to the main branch

jobs:
  deploy:
    name: Deploy to Google Cloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}  # GitHub Secret for your GCP Service Account Key

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and push Docker image to Google Container Registry
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app .

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy my-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated
